/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-11-30 04:37:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin.list;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Optional;

public final class user_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Semi/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SemiProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1666750741313L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Optional");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
 	Optional<String> opt = Optional.ofNullable(request.getParameter("page"));
	int p = Integer.parseInt(opt.orElse("1")); 

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/jquery-ui.min.css\">\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-3.6.1.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-ui.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css\" integrity=\"sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/admin.css\">\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("	$(function(){\r\n");
      out.write("		\r\n");
      out.write("		var id;\r\n");
      out.write("		\r\n");
      out.write("		fn_autoList();\r\n");
      out.write("		fn_searchList();\r\n");
      out.write("		fn_inputShow();\r\n");
      out.write("		fn_removeUser();\r\n");
      out.write("		fn_dormantUser();\r\n");
      out.write("		fn_restoreUser();\r\n");
      out.write("		fn_infoUser();\r\n");
      out.write("		\r\n");
      out.write("		$('.start_datepicker').datepicker({\r\n");
      out.write("			dateFormat: 'yymmdd',  // 실제로는 yyyymmdd로 적용됨\r\n");
      out.write("			changeMonth: true,\r\n");
      out.write("	      	changeYear: true\r\n");
      out.write("		});\r\n");
      out.write("		$('.end_datepicker').datepicker({\r\n");
      out.write("			dateFormat: 'yymmdd',  // 실제로는 yyyymmdd로 적용됨\r\n");
      out.write("			changeMonth: true,\r\n");
      out.write("	      	changeYear: true\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	function fn_autoList(){\r\n");
      out.write("		$('#userList, #span_cnt').empty();\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type : 'get',\r\n");
      out.write("			url : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/list/allUsers',\r\n");
      out.write("			data : 'page=' + ");
      out.print(p);
      out.write(",\r\n");
      out.write("			dataType : 'json',\r\n");
      out.write("			success : function(resData) {\r\n");
      out.write("				\r\n");
      out.write("				$('<span>').html('총 인원 수 : ' + resData.totalRecord)\r\n");
      out.write("				.append($('<span>').html('&nbsp;&nbsp;정상 회원 : ' + resData.userCnt))\r\n");
      out.write("				.append($('<span>').html('&nbsp;&nbsp;휴면 회원 : ' + resData.sleepUserCnt))\r\n");
      out.write("				.appendTo('#span_cnt');\r\n");
      out.write("				\r\n");
      out.write("				$('.pageWrap').html(resData.paging);\r\n");
      out.write("				\r\n");
      out.write("				if(resData.status == 200) {\r\n");
      out.write("\r\n");
      out.write("					$.each(resData.users, function(i, user){\r\n");
      out.write("\r\n");
      out.write("						$('<tr>')\r\n");
      out.write("						.append($('<td class=\"center\">').html(user.rn))\r\n");
      out.write("						.append($('<td class=\"center id\">').html($('<span class=\"user_info\">').text(user.userDTO.id)))\r\n");
      out.write("						.append($('<td class=\"blind\">').text('detail'))\r\n");
      out.write("						.append(user.sleepUserDTO.sleepDate == null ? $('<td class=\"center\">').html('정상회원') : $('<td class=\"center\">').html('휴면회원'))\r\n");
      out.write("						.append($('<td class=\"center\">').html(user.userDTO.point))\r\n");
      out.write("						.append(user.userDTO.snsType == null ? $('<td class=\"center\">').html('자체 회원') : $('<td class=\"center\">').html('Naver 가입'))\r\n");
      out.write("						.append($('<td class=\"center\">').html(user.userDTO.joinDate))\r\n");
      out.write("						.append($('<td class=\"center\">').html(user.userDTO.accessLogDTO.lastLoginDate))\r\n");
      out.write("						.append(user.userDTO.infoModifyDate == null ? $('<td class=\"center\">').html('') : $('<td class=\"center\">').html(user.userDTO.infoModifyDate))\r\n");
      out.write("						.append(user.sleepUserDTO.sleepDate == null ? $('<td class=\"center\">').html('') : $('<td class=\"sleepUser center\">').html(user.sleepUserDTO.sleepDate))\r\n");
      out.write("						.append($('<td class=\"center\">').html('<a class=\"dormant_icon\"><i class=\"fa-solid fa-user-check\"></i></a>'))\r\n");
      out.write("						.append($('<td class=\"center\">').html('<a class=\"restore_icon\"><i class=\"fa-solid fa-user-lock\"></i></a>'))\r\n");
      out.write("						.append($('<td class=\"center\">').html('<a class=\"retire_icon\"><i class=\"fa-solid fa-trash-can\"></i></a>'))\r\n");
      out.write("						.appendTo($('#userList'));\r\n");
      out.write("						\r\n");
      out.write("					});\r\n");
      out.write("				} else {\r\n");
      out.write("					alert(resData.message);\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	};\r\n");
      out.write("	\r\n");
      out.write("	function fn_searchList(){\r\n");
      out.write("		$('#btn_all').click(function(){\r\n");
      out.write("			fn_autoList();\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$('#btn_search').click(function(){\r\n");
      out.write("			$('#userList, #span_cnt').empty();\r\n");
      out.write("			\r\n");
      out.write("			if($('#query').val() == '' && $('#first').val() == '' && $('#last').val() == '' && $('#start').val() == '' && $('#stop').val() == '') {\r\n");
      out.write("				$('#column').val('');\r\n");
      out.write("			};\r\n");
      out.write("			var sleep = $('#sleepData');\r\n");
      out.write("			var modiDate = $('#modifyData');\r\n");
      out.write("			\r\n");
      out.write("			if($('#state').val() == '') {\r\n");
      out.write("				modiDate.show();\r\n");
      out.write("				sleep.show();\r\n");
      out.write("			} else {\r\n");
      out.write("				if($('#state').val() == 'active'){\r\n");
      out.write("					if($('#column').val() == 'SLEEP_DATE'){\r\n");
      out.write("						$('#column').val('');\r\n");
      out.write("					}\r\n");
      out.write("					sleep.hide();\r\n");
      out.write("					modiDate.show();\r\n");
      out.write("				} else {\r\n");
      out.write("					sleep.show();\r\n");
      out.write("					modiDate.hide();\r\n");
      out.write("				}\r\n");
      out.write("			};\r\n");
      out.write("			\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type : 'get',\r\n");
      out.write("				url : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/list/searchUsers',\r\n");
      out.write("				data : $('#frm_search').serialize(),\r\n");
      out.write("				dataType : 'json',\r\n");
      out.write("				success : function(resData) {\r\n");
      out.write("					var sleepCnt = '';\r\n");
      out.write("					if($('#state').val() == '') {\r\n");
      out.write("						sleepCnt = '&nbsp;&nbsp;휴면 회원 : ' + resData.sleepUserCnt;\r\n");
      out.write("					}\r\n");
      out.write("					$('<span>').html('총 인원 수 : ' + resData.totalRecord)\r\n");
      out.write("					.append($('<span>').html(sleepCnt))\r\n");
      out.write("					.appendTo('#span_cnt');\r\n");
      out.write("					\r\n");
      out.write("					$('.pageWrap').html(resData.paging);\r\n");
      out.write("					\r\n");
      out.write("					if(resData.status == 200) {\r\n");
      out.write("						$.each(resData.users, function(i, user){\r\n");
      out.write("							var tr = $('<tr>');\r\n");
      out.write("\r\n");
      out.write("							tr\r\n");
      out.write("							.append($('<input type=\"hidden\">').val())\r\n");
      out.write("							.append($('<td class=\"center\">').html(user.rn))\r\n");
      out.write("							.append($('<td class=\"center id\">').html($('<span class=\"info_user\">').text(user.userDTO.id)))\r\n");
      out.write("							.append($('<td class=\"blind\">').text('detail'))\r\n");
      out.write("							.append($('<td class=\"blind\">').text(user.sleepUserDTO.sleepDate == null ? '정상회원' : '휴면회원'))\r\n");
      out.write("							.append(user.sleepUserDTO.sleepDate == null ? $('<td class=\"center\">').html('정상회원') : $('<td class=\"center\">').html('휴면회원'))\r\n");
      out.write("							.append($('<td class=\"center\">').html(user.userDTO.point))\r\n");
      out.write("							.append(user.userDTO.snsType == null ? $('<td class=\"center\">').html('자체 회원') : $('<td class=\"center\">').html('Naver 가입'))\r\n");
      out.write("							.append($('<td class=\"center\">').html(user.userDTO.joinDate))\r\n");
      out.write("							.append($('<td class=\"center\">').html(user.userDTO.accessLogDTO.lastLoginDate));\r\n");
      out.write("							if($('#state').val() == ''){\r\n");
      out.write("								tr\r\n");
      out.write("								.append(user.userDTO.infoModifyDate == null ?  $('<td class=\"center\">').html('') : $('<td class=\"center\">').html(user.userDTO.infoModifyDate))\r\n");
      out.write("								.append(user.sleepUserDTO.sleepDate == null ? $('<td class=\"center\">').html('') : $('<td class=\"sleepUser center\">').html(user.sleepUserDTO.sleepDate))\r\n");
      out.write("							}else{\r\n");
      out.write("								tr\r\n");
      out.write("								.append(user.sleepUserDTO.sleepDate == null ? $('<td class=\"center\">').html(user.userDTO.infoModifyDate) : $('<td class=\"sleepUser center\">').html(user.sleepUserDTO.sleepDate))\r\n");
      out.write("							}\r\n");
      out.write("							tr\r\n");
      out.write("							.append($('<td class=\"center\">').html('<a class=\"dormant_icon\"><i class=\"fa-solid fa-user-check\"></i></a>'))\r\n");
      out.write("							.append($('<td class=\"center\">').html('<a class=\"restore_icon\"><i class=\"fa-solid fa-user-lock\"></i></a>'))\r\n");
      out.write("							.append($('<td class=\"center\">').html('<a class=\"retire_icon\"><i class=\"fa-solid fa-trash-can\"></i></a>'))\r\n");
      out.write("							tr.appendTo($('#userList'));\r\n");
      out.write("							\r\n");
      out.write("						});\r\n");
      out.write("					} else {\r\n");
      out.write("						alert(resData.message);\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function fn_removeUser(){\r\n");
      out.write("		var userType = '';\r\n");
      out.write("		$(document).on('click', '.retire_icon', function(event){\r\n");
      out.write("			id = $(this).parent().parent().children().first().next().text();\r\n");
      out.write("			if(confirm(id + '회원을 삭제하시겠습니까?')){\r\n");
      out.write("				\r\n");
      out.write("				if($(this).parent().prev().prev().prev().hasClass('sleepUser')){\r\n");
      out.write("					userType = 'SLEEP_USERS';\r\n");
      out.write("				} else {\r\n");
      out.write("					userType = 'USERS';\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					type : 'post',\r\n");
      out.write("					url : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/user/retire',\r\n");
      out.write("					data : 'userType=' + userType + '&id=' + id,\r\n");
      out.write("					dataType : 'json',\r\n");
      out.write("					success : function(resData){\r\n");
      out.write("						alert(resData.message);\r\n");
      out.write("						fn_autoList();\r\n");
      out.write("					}\r\n");
      out.write("				});	// ajax\r\n");
      out.write("				\r\n");
      out.write("			};// confirm	\r\n");
      out.write("		});	// event\r\n");
      out.write("	}	// fn\r\n");
      out.write("	\r\n");
      out.write("	function fn_dormantUser(){\r\n");
      out.write("		$(document).on('click', '.dormant_icon', function(event){\r\n");
      out.write("			id = $(this).parent().parent().children().first().next().text();\r\n");
      out.write("			\r\n");
      out.write("			if(confirm(id + '회원을 휴면 회원으로 전환 하시겠습니까?')){\r\n");
      out.write("				\r\n");
      out.write("				if($(this).parent().prev().hasClass('sleepUser')){\r\n");
      out.write("					alert('이미 휴면 회원입니다.');\r\n");
      out.write("					event.preventDefault();\r\n");
      out.write("					return;\r\n");
      out.write("					\r\n");
      out.write("				} else {\r\n");
      out.write("					\r\n");
      out.write("					$.ajax({\r\n");
      out.write("						type : 'post',\r\n");
      out.write("						url : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/user/dormant',\r\n");
      out.write("						data : 'id=' + id,\r\n");
      out.write("						dataType : 'json',\r\n");
      out.write("						success : function(resData){\r\n");
      out.write("							alert(resData.message);\r\n");
      out.write("							fn_autoList();\r\n");
      out.write("						}\r\n");
      out.write("					});\r\n");
      out.write("				};\r\n");
      out.write("			};\r\n");
      out.write("		});\r\n");
      out.write("	};\r\n");
      out.write("	\r\n");
      out.write("	function fn_restoreUser(){\r\n");
      out.write("		$(document).on('click', '.restore_icon', function(event){\r\n");
      out.write("			id = $(this).parent().parent().children().first().next().text();\r\n");
      out.write("			if(confirm(id + '회원을 정상 회원으로 전환 하시겠습니까?')){\r\n");
      out.write("				if($(this).parent().prev().prev().hasClass('sleepUser')){\r\n");
      out.write("					\r\n");
      out.write("					$.ajax({\r\n");
      out.write("						type : 'post',\r\n");
      out.write("						url : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/user/restore',\r\n");
      out.write("						data : 'id=' + id,\r\n");
      out.write("						dataType : 'json',\r\n");
      out.write("						success : function(resData){\r\n");
      out.write("							alert(resData.message);\r\n");
      out.write("							fn_autoList();\r\n");
      out.write("						}\r\n");
      out.write("					});\r\n");
      out.write("					\r\n");
      out.write("				} else {\r\n");
      out.write("					\r\n");
      out.write("					alert('이미 정상 회원입니다.');\r\n");
      out.write("					event.preventDefault();\r\n");
      out.write("					return;\r\n");
      out.write("				\r\n");
      out.write("				};\r\n");
      out.write("			};\r\n");
      out.write("		});\r\n");
      out.write("	};\r\n");
      out.write("	\r\n");
      out.write("	function fn_infoUser(){\r\n");
      out.write("		$(document).on('click', '.user_info', function(event){\r\n");
      out.write("			var id = $(this).text();\r\n");
      out.write("			var detail = $(this).parent().next().text();\r\n");
      out.write("			var state = $(this).parent().next().next().text();\r\n");
      out.write("			location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/user/detail?id=\" + id + \"&type=\" + detail + \"&state=\" + state;\r\n");
      out.write("		})\r\n");
      out.write("	};\r\n");
      out.write("	\r\n");
      out.write("	function fn_inputShow(){\r\n");
      out.write("		\r\n");
      out.write("		$('#area2').hide();\r\n");
      out.write("		$('#area3').hide();\r\n");
      out.write("		\r\n");
      out.write("		$('#area2').css('display', 'none');\r\n");
      out.write("\r\n");
      out.write("		$('#column').change(function(){\r\n");
      out.write("			$('.input').val('');\r\n");
      out.write("			let combo = $(this);\r\n");
      out.write("			if(combo.val() == 'ID' || combo.val() == ''){\r\n");
      out.write("				$('#area1').show();\r\n");
      out.write("				$('#area2').hide();\r\n");
      out.write("				$('#area3').hide();\r\n");
      out.write("			} else if(combo.val() == 'POINT'){\r\n");
      out.write("				$('#area1').hide();\r\n");
      out.write("				$('#area2').show();\r\n");
      out.write("				$('#area3').hide();\r\n");
      out.write("			} else {\r\n");
      out.write("				$('#area1').hide();\r\n");
      out.write("				$('#area2').hide();\r\n");
      out.write("				$('#area3').show();\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	};\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<header>\r\n");
      out.write("	<div class=\"head_bar\">\r\n");
      out.write("		<div id=\"logo_div\">\r\n");
      out.write("			<a href=\"../index.jsp\"><img id=\"logo\" src=\"https://www.gdu.co.kr/images/main/logo.png\"></a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<ul class=\"gnb_barAll\">\r\n");
      out.write("			<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/menu\"  class=\"gnb_bar\">전체메뉴</a></li>\r\n");
      out.write("			<li><span class=\"snb_bar\"></span><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/list/board\" class=\"gnb_bar\">게시판 관리</a></li>\r\n");
      out.write("			<li><span class=\"snb_bar\"></span><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/list/user\" class=\"gnb_bar\">회원관리</a></li>\r\n");
      out.write("			<li><span class=\"snb_bar\"></span><a href=\"#\"  class=\"gnb_bar\">게시판 가기</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("</header>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"allForm\">\r\n");
      out.write("		<div class=\"queryForm\">\r\n");
      out.write("			<div class=\"cnt_div\">\r\n");
      out.write("				<span id=\"span_cnt\"></span>\r\n");
      out.write("			</div>\r\n");
      out.write("			<form id=\"frm_search\">\r\n");
      out.write("				<select id=\"state\" name=\"state\" class=\"select\">\r\n");
      out.write("					<option value=\"\">전체</option>\r\n");
      out.write("					<option value=\"active\">정상회원</option>\r\n");
      out.write("					<option value=\"sleep\">휴면회원</option>\r\n");
      out.write("				</select>\r\n");
      out.write("				<select id=\"column\" name=\"column\" class=\"select\">\r\n");
      out.write("					<option value=\"\">:::선택:::</option>\r\n");
      out.write("					<option value=\"ID\">아이디</option>\r\n");
      out.write("					<option value=\"JOIN_DATE\">가입일</option>\r\n");
      out.write("					<option id=\"sleepOpt\" value=\"SLEEP_DATE\">휴면일자</option>\r\n");
      out.write("					<option value=\"POINT\">포인트</option>\r\n");
      out.write("				</select>\r\n");
      out.write("				<input type=\"hidden\" name=\"page\" value=\"");
      out.print(p);
      out.write("\">\r\n");
      out.write("				<span id=\"area1\">\r\n");
      out.write("					<input type=\"text\" id=\"query\" name=\"query\" class=\"input searchBox\">\r\n");
      out.write("				</span>\r\n");
      out.write("				<span id=\"area2\">\r\n");
      out.write("					<input type=\"text\" id=\"first\" name=\"first\" class=\"input searchBox\">\r\n");
      out.write("					~\r\n");
      out.write("					<input type=\"text\" id=\"last\" name=\"last\" class=\"input searchBox\">\r\n");
      out.write("				</span>\r\n");
      out.write("				<span id=\"area3\">\r\n");
      out.write("					<input type=\"text\" id=\"start\" name=\"start\" class=\"start_datepicker input searchBox\">\r\n");
      out.write("					~\r\n");
      out.write("					<input type=\"text\" id=\"stop\" name=\"stop\" class=\"end_datepicker input searchBox\">\r\n");
      out.write("				</span>\r\n");
      out.write("				<span>\r\n");
      out.write("					<input type=\"button\" value=\"검색\" id=\"btn_search\" class=\"btn_primary\">\r\n");
      out.write("					<input type=\"button\" value=\"전체회원조회\" id=\"btn_all\" class=\"btn_primary\">\r\n");
      out.write("				</span>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("		<table class=\"tbl_user\">\r\n");
      out.write("			<thead class=\"head_font thead_user\">\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>순번</td>\r\n");
      out.write("					<td>아이디</td>\r\n");
      out.write("					<td>상태</td>\r\n");
      out.write("					<td>포인트</td>\r\n");
      out.write("					<td>가입종류</td>\r\n");
      out.write("					<td>가입일</td>\r\n");
      out.write("					<td>마지막접속일</td>\r\n");
      out.write("					<td id=\"modifyData\">정보변경일</td>\r\n");
      out.write("					<td id=\"sleepData\">휴면날짜</td>\r\n");
      out.write("					<td>휴면전환</td>\r\n");
      out.write("					<td>휴면해제</td>\r\n");
      out.write("					<td>강제탈퇴</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</thead>\r\n");
      out.write("			<tbody id=\"userList\">\r\n");
      out.write("			</tbody>\r\n");
      out.write("		</table>\r\n");
      out.write("		<div class=\"paginate\">\r\n");
      out.write("			<div class=\"pageWrap\">\r\n");
      out.write("				");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${paging}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/admin/list/user.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/admin/list/user.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/admin/list/user.jsp(5,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
